CADDY_VERSION=v2.10.2

diff --git a/caddy/Dockerfile b/caddy/Dockerfile
--- a/caddy/Dockerfile
+++ b/caddy/Dockerfile
@@ -1,21 +1,58 @@
-# Release links:
-# https://hub.docker.com/_/caddy
+FROM alpine:3.22
 
-# Versions of images
-ARG caddy_version="2.10-alpine"
+# https://github.com/caddyserver/caddy/releases
+ARG CADDY_VERSION=v2.10.2
 
-# Caddy base image
-FROM docker.io/library/caddy:${caddy_version}
-LABEL maintainer="Jinndi <alncores@gmail.com>"
+RUN apk add --no-cache \
+	ca-certificates \
+	libcap \
+	mailcap \
+  bash
 
-# Add bash
-RUN apk add --no-cache bash
+RUN set -eux; \
+	mkdir -p \
+		/config/caddy \
+		/data/caddy \
+		/etc/caddy
+
+ENV CADDY_VERSION=${CADDY_VERSION}
 
 # Copy scripts to container
 COPY ./entrypoint.sh /entrypoint.sh
 
-# Making scripts executable
-RUN chmod +x /entrypoint.sh
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64)  binArch='amd64';checksum='747df7ee74de188485157a383633a1a963fd9233b71fbb4a69ddcbcc589ce4e2cc82dacf5dbbe136cb51d17e14c59daeb5d9bc92487610b0f3b93680b2646546' ;; \
+		armv7)   binArch='armv7';checksum='215af42cf952726d962c9753a12c04248781221b66df8b7110726fa7905d7a5c2e50056e0b47ab3c709d3dcfb48fde0f11e184a6950de0a2ddf941d3e503d07b' ;; \
+		aarch64) binArch='arm64';checksum='6ce061a690312ab38367df3c5d5f89a2e4a263e7300d300d87356211bb81e79b15933e6d6203e03fbf26f15cc0311f264805f336147dbdd24938d84b57a4421c' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O /tmp/caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/${CADDY_VERSION}/caddy_${CADDY_VERSION#v}_linux_${binArch}.tar.gz"; \
+	echo "$checksum  /tmp/caddy.tar.gz" | sha512sum -c; \
+	tar x -z -f /tmp/caddy.tar.gz -C /usr/bin caddy; \
+	rm -f /tmp/caddy.tar.gz; \
+	setcap cap_net_bind_service=+ep /usr/bin/caddy; \
+	chmod +x /usr/bin/caddy /entrypoint.sh; \
+	caddy version
 
-# Launch entrypoint
+# See https://caddyserver.com/docs/conventions#file-locations for details
+ENV XDG_CONFIG_HOME /config
+ENV XDG_DATA_HOME /data
+
+LABEL org.opencontainers.image.version=${CADDY_VERSION}
+LABEL org.opencontainers.image.title=Caddy
+LABEL org.opencontainers.image.description="a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go"
+LABEL org.opencontainers.image.url=https://caddyserver.com
+LABEL org.opencontainers.image.documentation=https://caddyserver.com/docs
+LABEL org.opencontainers.image.vendor="Light Code Labs"
+LABEL org.opencontainers.image.licenses=Apache-2.0
+LABEL org.opencontainers.image.source="https://github.com/caddyserver/caddy-docker"
+LABEL maintainer="Jinndi <alncores@gmail.com>"
+
+EXPOSE 443
+EXPOSE 443/udp
+
+WORKDIR /srv
+
 ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
